# Site settings
author: Osha G
title: Changer Danger
header-img: img/home-bg.png
email: ogroetz@gmail.com
copyright_name: Osha G
description: > # this means to ignore newlines until "baseurl:"
  Dancing with the devil of life changing events.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  osha7

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
